const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/zhaos/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path = require('path');
const assert = require('assert').strict;

let browser;
(async () => {
  browser = await chromium.launch({ channel: 'msedge', headless: true, args:['--enable-webgl','--ignore-gpu-blocklist'] });
  const page = await browser.newPage({ viewport:{width:1360,height:850} });
  const errors = [];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{ if(m.type()==='error'){ errors.push(m.text()); console.error('BROWSER:',m.text()); } });
  await page.goto('http://127.0.0.1:4173/simulator/');
  await page.screenshot({path:path.join(__dirname,'web-intro.png')});
  await page.locator('#start').click();
  await page.waitForFunction(()=>window.__drivingState, {timeout:45000});
  await page.waitForTimeout(4000);
  await page.screenshot({path:path.join(__dirname,'web-chase.png')});
  const initial = await page.evaluate(()=>window.__drivingState);
  assert.equal(initial.speed,0);
  assert.equal(await page.locator('#intro').isVisible(),false);
  await page.keyboard.down('w');
  await page.waitForTimeout(1300);
  await page.keyboard.up('w');
  const moved = await page.evaluate(()=>window.__drivingState);
  assert(moved.speed>0 && moved.z < initial.z, 'W must move the exported vehicle');
  await page.keyboard.down('s');
  await page.waitForTimeout(800);
  await page.keyboard.up('s');
  assert((await page.evaluate(()=>window.__drivingState.speed))<1,'S must stop the exported vehicle');
  await page.locator('#camera').click();
  await page.waitForTimeout(400);
  assert.equal(await page.evaluate(()=>window.__drivingState.camera),'cockpit');
  await page.screenshot({path:path.join(__dirname,'web-cockpit.png')});
  await page.locator('#camera').click();
  await page.waitForTimeout(600);
  await page.screenshot({path:path.join(__dirname,'web-chase.png')});
  await page.locator('#pause').click();
  await page.waitForTimeout(200);
  assert.equal(await page.evaluate(()=>window.__drivingState.paused),true);
  await page.locator('#reset').click();
  await page.waitForTimeout(200);
  const reset=await page.evaluate(()=>window.__drivingState);
  assert.equal(reset.z,35); assert.equal(reset.score,100); assert.equal(reset.paused,false);
  await page.locator('#mission').selectOption('parking');
  await page.waitForFunction(()=>window.__drivingState.mission==='parking',null,{timeout:5000});
  await page.locator('#signal_right').click();
  await page.waitForTimeout(200);
  assert.equal(await page.evaluate(()=>window.__drivingState.signal),'right');
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(300);
  await page.screenshot({path:path.join(__dirname,'web-mobile-portrait.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.locator('#mission').selectOption('cruise');
  await page.waitForFunction(()=>window.__drivingState.mission==='cruise');
  const client=await page.context().newCDPSession(page);
  const throttle=await page.locator('[data-drive="throttle"]').boundingBox();
  const left=await page.locator('[data-drive="left"]').boundingBox();
  const points=[{x:throttle.x+throttle.width/2,y:throttle.y+throttle.height/2,id:1},{x:left.x+left.width/2,y:left.y+left.height/2,id:2}];
  await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[points[0]]});
  await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});
  await page.waitForTimeout(1100);
  const touched=await page.evaluate(()=>window.__drivingState);
  assert(touched.speed>0 && touched.steer>0,'Two-finger touch must steer and accelerate simultaneously');
  await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.waitForTimeout(200);
  assert.equal(await page.locator('[data-drive].active').count(),0,'Releasing touch must clear all held controls');
  await page.setViewportSize({width:844,height:390});
  await page.waitForTimeout(300);
  await page.screenshot({path:path.join(__dirname,'web-mobile-landscape.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  console.log(JSON.stringify({initial,moved,reset,errors},null,2));
  await browser.close();
  if (errors.length) process.exitCode=1;
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
